apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - chart: crossplane
      repoURL: https://charts.crossplane.io/stable
      targetRevision: 1.14.5
      helm:
        releaseName: crossplane
    - repoURL: "https://github.com/josemimbre/crossplane-aws-example.git"
      path: crossplane-providers
  destination:
    server: "https://kubernetes.default.svc"
    namespace: crossplane-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
